name: CI Katalon Demo
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Cho phép bạn nhấn nút chạy bằng tay khi cần

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Katalon Tests
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '9.6.0'
          args: '-noSplash -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey=${{ secrets.KATALON_API_KEY }}'
