name: CI Katalon Demo
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Cho phép bạn nhấn nút chạy bằng tay khi cần

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Katalon Tests
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '9.6.0'
          # Quan trọng: Thêm -projectPath="${{ github.workspace }}" vào đầu args
          args: '-noSplash -runMode="console" -projectPath="${{ github.workspace }}" -retry=0 -testSuitePath="Test Suites/Regression Test Suite 1" -browserType="Chrome" -apiKey=${{ secrets.KATALON_API_KEY }}'
